config/routes.rb
Bookshare::Application.routes.draw do
  
  resources :static_pages do
    collection do
      get :membership_overview,:membership_options,:qualifications,:gift_memberships,:search_text,:search_book,
      :search_author
    end
  end

  root :to => "static_pages#index" 
  
  

end

app/models/bookshare_api.rb
require 'rubygems'
require 'httparty'
require 'json'
 
class BookshareApi
  include HTTParty
  base_uri 'api.bookshare.org'
  default_params :api_key => 'xew4s5nagrhf5g6rh8jh2x4j'
  format :json
 

  def self.isbn_lookup(query)
     get("/book/isbn/#{query}/format/json")
  end
  
  
  def self.book_id(query)
     get("/book/id/#{query}/format/json")
 end
  
  
  def self.full_text_search(query,limit)
     get("/book/searchFTS/#{query}/page/1/limit/#{limit}/format/json" )
  end

  
  def self.title_search(query,limit)
      get("/book/search/title/#{query}/page/1/limit/#{limit}/format/json" )
  end
     
    
  def self.author_search(query,limit)
      get("/book/search/author/#{query}/page/1/limit/#{limit}/format/json" )
  end
 
 def self.titleauthor_search(query,limit)
    get("/book/search/#{query}/page/1/limit/#{limit}/format/json" )
 end
 
 def self.datepublished_search(query,limit)
     get("/book/search/since/#{query}/page/1/limit/#{limit}/format/json" )
 end
 
 def self.latest_browsed(query,limit)
   get("/book/latest/page/#{query}/page/1/limit/#{limit}/format/json")
 end
 
 def self.popular_browsed(query,limit)
   get("/book/popular/page/#{query}/page/1/limit/#{limit}/format/json")
 end
 
 def self.category_list(query,limit)
   get("/book/reference/category/list/#{query}/page/1/limit/#{limit}/format/json")
 end

 def self.category_search(query,limit)
    get("/book/search/category/#{query}/page/1/limit/#{limit}/format/json")
 end

def self.grade_list(query,limit)
   get("/reference/grade/list/#{query}/page/1/limit/#{limit}/format/json")
end
 
 def self.grade_search(query,limit)
   get("/book/search/grade/#{query}/page/1/limit/#{limit}/format/json")
 end
 
 def self.combinemultiple_search(query,limit)
   get("/book/search/grade/#{query}/page/1/limit/#{limit}/format/json")
 end
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]
  require 'will_paginate/array'
  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @static_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url }
      format.json { head :no_content }
    end
  end
  
  def membership_overview
    puts "---------------------------"
  end
  
  def membership_options
    
  end
  
  def qualifications
    
  end
  
  def gift_memberships
    
  end
  
  
  def search_book
    puts "-----------#{params}"
    @id=params[:id]
    @response=BookshareApi.book_id(@id)
    @result = JSON.parse(@response.body)
    @book=@result["bookshare"]["book"]["metadata"]
  end
  
  def search_author
      puts "-----------#{params}"
  end

  def search_text
    puts "------#{params[:searchtxt]}"
    @search_txt=params[:searchtxt]
    @response=BookshareApi.full_text_search(@search_txt,100)
    @result = JSON.parse(@response.body)
    # puts "-----#{@result.keys}"
    @searched_result=(@result['bookshare']['book']['list']['result']).paginate(:page => params[:page],:per_page => 5)
    # respond_to do |format|
     # format.json { render :json => JSON.parse(@result) }
     # format.html { render  "search_text.html.erb"}
   # end
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_dashboard_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">BookShare India</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">






                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Membership<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="Membership">
                        <!--<li><a tabindex="-1" href="../default/">Default</a></li>-->
                        <!--<li class="divider"></li>-->
                        <li><a tabindex="-1" href="/static_pages/membership_overview">Membership Overview</a></li>
                        <li><a tabindex="-1" href="/static_pages/membership_options">Membership Options</a></li>
                        <li><a tabindex="-1" href="/static_pages/qualifications">Qualifications</a></li>
                        <li><a tabindex="-1" href="/static_pages/gift_memberships">Gift Memberships</a></li>
                        <li><a tabindex="-1" href="International%20Membership.html">Internal Membership</a></li>
                        <li><a tabindex="-1" href="#">Sign Up</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Getting Started<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="Getting Started">
                        <li><a tabindex="-1" href="Getting%20Started%20Overview.html">Getting Started Overview</a></li>
                        <li><a tabindex="-1" href="Find Books.html">Find Books</a></li>
                        <li><a tabindex="-1" href="Download%20Books.html">Downloads Books</a></li>
                        <li><a tabindex="-1" href="Read%20Books.html">Reads Books</a></li>
                        <li><a tabindex="-1" href="Reading%20Tools.html">Reading Tools</a></li>
                    </ul>
                </li>


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">About Us<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="About Us">
                        <!--<li><a tabindex="-1" href="../default/">Default</a></li>-->
                        <!--<li class="divider"></li>-->
                        <li><a tabindex="-1" href="#">About Us Overview</a></li>
                        <li><a tabindex="-1" href="#">Mission</a></li>
                        <li><a tabindex="-1" href="#">How Bookshare Works</a></li>
                        <li><a tabindex="-1" href="#">News and Events</a></li>
                        <li><a tabindex="-1" href="#">Leadership</a></li>
                        <li><a tabindex="-1" href="#">Partners</a></li>
                        <li><a tabindex="-1" href="#">Majors Donors</a></li>
                        <li><a tabindex="-1" href="#">Member Stories</a></li>
                        <li><a tabindex="-1" href="#">Legal Information</a></li>
                    </ul>
                </li>


                <!-- <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">QuickLinks<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="QuickLinks"> -->
                        <!--<li><a tabindex="-1" href="../default/">Default</a></li>-->
                        <!--<li class="divider"></li>-->
                        <!-- <li><a tabindex="-1" href="#">Newspapers & Magazines</a></li>
                        <li><a tabindex="-1" href="#">Trainings</a></li>
                        <li><a tabindex="-1" href="#">Donate Now</a></li>

                    </ul>
                </li> -->

                <li>
                    <a href="http://news.bootswatch.com">Contact Us</a>
                </li>

                <!--<login>-->
                    <li>
                        <a data-toggle="modal" href="#myModal">Login</a>
                    </li>



                         <!--<loginin>-->


                    </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>
<%= render 'layouts/modal_box'%> 

app/views/layouts/_footer.html.erb
<hr>

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; EzzieInfosystem</p>
            </div>
        </div>
    </footer>

app/views/layouts/_modal_box.html.erb
<!--modal-->

<div class="text-center">
 </div>

<div class="modal fade" id="myModal">
	<div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Log-in</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
    		<label for="exampleInputEmail1">Email address</label>
    		<input class="form-control" id="exampleInputEmail1" placeholder="Enter email" type="email">
  		  </div>
		  <div class="form-group">
		  	<label for="exampleInputPassword1">Password</label>
			<input class="form-control" id="exampleInputPassword1" placeholder="Password" type="password">
		  </div>
          <p class="text-right"><a href="#">Forgot password?</a></p>
        </div>
        <div class="modal-footer">
          <a href="#" data-dismiss="modal" class="btn">Close</a>
          <a href="#" class="btn btn-primary">Log-in</a>
        </div>
      </div>
    </div>
</div>



<!--modal-->

app/views/layouts/_sidebar.html.erb
        <div class="col-lg-4 sidebar">
            <div class="well">
            	 <h4>Search</h4>
            	<form action="/static_pages/search_text" method="get">
                 <div class="input-group">
                    <input name="searchtxt" type="text" class="form-control">
              <span class="input-group-btn">
                <button class="btn btn-default" id="search-btn" type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
                </div><!-- /input-group -->
			</form>
                <div class="row">
                    <div class="col-lg-5">
                     <a href="#">Advanced Search</a>
                    </div>
                    <div class="col-lg-2">
                     <a href="#">Browse</a>
                    </div>
                 </div>
            </div><!-- /well -->
            <div class="well">
                <h4>Quick Links</h4>
                <div class="row">
                    <div class="col-lg-7">
                        <ul class="list-unstyled">
                            <li><a href="#">Newspaper & Magazines</a></li>
                            <li><a href="#">Traning</a></li>
                            <li><a href="#">Donate Now</a></li>
                            <!--<li><a href="#wild-animals">Wild Animals</a></li>-->
                        </ul>
                    </div>

                </div>
            </div><!-- /well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Support our Veterans!

                    Help support Veterans with print disabilities by joining Benetech's CrowdRise campaign. Check out the largest ever CrowdRise.com challenge from the Skoll Foundation and learn how you can help a Veteran today!</p>
            </div><!-- /well -->
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	
	<%= render 'layouts/dashboard_header'%>
	
	<div class="container">
    <div class="row">
        <div class="col-lg-8">
           <div class="well">
            <!-- blog entry -->
            <h1 id="logo"><a href="#"><img src="/assets/share.png" width="278"></a></h1>
            <p class="lead"><a href="index.html">An Accessible Online Library
                for people with print disabilities</a></p>                
            </div>

      <div id="content" class="panel panel-default">
	     <%= yield %>
	   </div><!--content-->

        </div>
        
		<%= render 'layouts/sidebar'%>

    </div><!--row -->

    <%= render 'layouts/footer'%>

</div><!-- /.container -->
<div class="modal"><!-- Place at bottom of page --></div>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/gift_memberships.html.erb
 <div class="panel-heading"><h4>Gift Memberships</h4></div>
    <div class="panel-body">





            <p>You can purchase a Bookshare&reg; membership for somebody with a
                <a href="/_/membership/qualifications">qualifying disability</a>, such as visual
                impairment, learning disability or physical disability. You can also order an
                embossed Braille book as a gift for anyone in the U.S.</p>

            <p>Memberships are $50 a year plus a one-time $25 set up fee for new Members. A
                Bookshare membership provides unlimited downloads for a year. There are no
                per-book download charges or other costs.</p>

            <p><strong>TIP</strong>: All U.S. students are eligible for free memberships as
                part of an award from the U.S. Department of Education Office of Special
                Education Programs (OSEP).</p>

            <p>After receiving the gift membership, the recipient will need to register on
                the Bookshare website (if under 18, a parent will need to sign the Member
                Agreement) and provide Proof of Disability.</p>

            <p>Please <a href="http://www.bookshare.org/contactUs">Contact Us</a> if you
                would like to purchase a gift membership.</p>

            <p>For information on ordering a Braille book, visit the
                <a href="http://www.bookshare.org/_/gettingStarted/readBooks">Read Books</a>
                page.</p>

            <p>If you are interested in making a
                <a href="/_/contribute/donateFunds">financial contribution</a> or volunteering
                to help Bookshare, <a href="/_/contribute/overview">visit the Contribute
                    page</a>.</p>

            <p>&nbsp;</p>




        </div><!-- End .oneCol .static -->

app/views/static_pages/index.html.erb
<div id="myCarousel" class="carousel slide">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="assets/slide.jpg" width="300">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>BooKShare</h1>
                                <pthis is="" an="" example="" layout="" with="" carousel="" that="" uses="" the="" bootstrap="" 3="" styles.<="" small=""><p></p>
                                <p><a class="btn btn-lg btn-primary" href="http://getbootstrap.com">Sign Up</a>
                                </p></pthis></div>
                        </div>
                    </div>
                    <div class="item">
                        <img src="assets/library6.jpg" width="300">
                        <div class="container">
                            <div class="carousel-caption">
                                <!--<h1>Changes to the Grid</h1>-->
                                <p>An Accessible Online Library for people with print disabilities</p>
                                <
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img src="assets/slide2.jpg" width="300">
                        <div class="container">
                            <div class="carousel-caption">
                                <!--<h1>Percentage-based sizing</h1>-->
                                <p>An Accessible Online Library for people with print disabilities</p>
                                <!--<p><a class="btn btn-large btn-primary" href="#">Sign Up</a></p>-->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="icon-next"></span>
                </a>
            </div>
            <!-- /.carousel -->

app/views/static_pages/membership_options.html.erb
<div class="panel-heading"><h4>Membership Options</h4></div>
                <div class="panel-body">
                    <h2>Joining Bookshare offers a number of benefits</h2>
                    <ul>
                        <li>Access to the world’s largest online library of accessible reading materials (books, textbooks, newspapers and magazines) for people with print disabilities.</li>
                        <li>An unlimited library card, providing a steady flow and variety of new reading materials anytime you want, seven days a week, 24 hours a day.</li>
                        <li>Free access technology for reading books in the DAISY format.</li>
                    </ul>
                    <p>
                        Membership in Bookshare&reg; is available to individuals with
                        <a href="/_/membership/qualifications">qualifying print disabilities</a>
                        and to organizations supporting those individuals.
                    </p>
                    <ul>
                        <li><a href="#IndividualMemberships">Individual Memberships</a></li>
                        <li><a href="#OrganizationalMemberships">Organizational Memberships</a></li>
                        <li><a href="#GiftMemberships">Gift Memberships</a></li>
                    </ul>
                    <p>
                        Through an award from the U.S. Department of Education Office of Special
                        Education Programs (OSEP), Bookshare offers free memberships to U.S.
                        schools and qualifying U.S. students. Read more about the
                        <a href="/_/aboutUs/2012/07/benetechWinsAward">OSEP award</a>.
                    </p>

                    <a name="IndividualMemberships" id="IndividualMemberships"></a>
                    <h2>Individual Memberships</h2>
                    <p>
                        An individual membership allows any individual with a qualifying print
                        disability to download books from Bookshare. Individuals can have their
                        own individual membership and can also be listed on an organization’s
                        membership.
                    </p>
                    <p>
                        Students under the age of 18 need permission from a parent or guardian to
                        sign up with Bookshare.
                    </p>
                    <p>
                        The default number of downloads per month is 100 books. Individuals wanting
                        more may <a href="/contactUs?sendInfoOn=My%20Number%20of%20Book%20Downloads">increase this default by contacting Bookshare</a>.
                    </p>
                    <div class="table-responsive">

                        <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Membership Type</th>
                            <th scope="col">Cost</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row" class="row">Qualifying U.S. students:
                                <ul>
                                    <li>K-12 (public and private)</li>
                                    <li>Home-schooled students</li>
                                    <li>Post-secondary (public and private)</li>
                                    <li>Adult education</li>
                                </ul>

                            </th><td>
                            Free (<a href="/_/aboutUs/2012/07/benetechWinsAward"> Currently funded by OSEP</a>)
                        </td>
                        </tr>
                        <tr>
                            <th scope="row" class="row">All other U.S. individuals</th>
                            <td>$75 ($25 one-time set up fee + $50 annual fee) </td>
                        </tr>
                        <tr>
                            <th scope="row" class="row">International individuals</th>
                            <td>Generally same as U.S. individuals, but some countries (e.g. India)
                                have lower fees. <a href="/_/membership/international"> Visit the
                                    International page for more information</a>. </td>
                        </tr>
                        </tbody>
                    </table>

                    <p>
                    </p><form action="/signUpMember">
                    <input type="submit" value="Sign up for an individual membership" class="button">
                </form>
                    <p></p>

                    <br><br>
                    <a name="OrganizationalMemberships" id="OrganizationalMemberships"></a>
                    <h2>Organizational Memberships</h2>
                    <p>
                        Organizations that serve adults and students with print disabilities may
                        register for <a href="/signUpOrganization">organizational memberships</a>.
                    </p>
                    <p>
                        Organizations that might want to register for membership include: schools at
                        all levels, libraries, rehabilitation agencies, resource centers, retirement
                        communities and group homes both inside and outside the U.S.
                    </p>
                    <p>
                        With this type of membership, teachers and/or staff members (Sponsors)
                        download books for their students and/or clients (Members). These
                        organizations provide Bookshare with:
                    </p>
                    <ul>
                        <li>Roster of Sponsors: teachers and/or staff members who will download the books</li>
                        <li>Roster of Members: students and/or clients with <a href="/_/membership/qualifications">qualifying print disabilities</a> who will read the books</li>
                    </ul>
                    <p>
                        Organizations can also recommend that their Members sign up for individual
                        memberships so they can download books on their own.
                    </p>
                    <p>
                        Currently, memberships for U.S. educational institutions are <a href="/_/aboutUs/2012/07/benetechWinsAward">funded by OSEP</a>,
                        and are therefore free. Other organizations can purchase
                        memberships as described in the table below.
                    </p>
                    <p>
                        U.S. public K-12 schools with memberships have access to Bookshare’s
                        NIMAC-sourced (National Instructional Materials Accessibility Center)
                        textbooks and can download these books for students who are Chafee qualified
                        and have an Individualized Education Plan (IEP).
                    </p>
                    <h3>Organizational Memberships Options</h3>

                    <div class="table-responsive">

                    <table class="table table-bordered">
                        <thead>
                        resultsTable
                        <tr>
                            <th scope="col">Membership Type</th>
                            <th scope="col">Cost</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th scope="row" >U.S. schools:
                                <ul>
                                    <li>K-12</li>
                                    <li>Colleges and universities</li>
                                    <li>All other educational institutions</li>
                                </ul>
                            </th>
                            <td>Free for all U.S. schools (<a href="/_/aboutUs/2012/07/benetechWinsAward">Funded by OSEP</a>)</td>
                        </tr>
                        <tr>
                            <th scope="row" >All other U.S. organizations</th>
                            <td>By Number of Books
                                <ul>
                                    <li>30 book block $300</li>
                                    <li>60 book block $450</li>
                                    <li>100 book block $600</li>
                                </ul>
                                Or, <br>
                                by Funding Individual Memberships <br>
                                $75 ($25 one-time set up fee + $50 annual fee) </td>
                        </tr>
                        <tr>
                            <th scope="row" >All international organizations</th>
                            <td>Generally same as U.S. organizations, but some countries (e.g. India) have lower fees.
                                <a href="/_/membership/international">Visit the International page for more information</a>.
                            </td>
                        </tr>
                        </tbody>
                    </table>
                        </div>

                    </div>


                    <p>
                    </p><form action="/signUpOrganization">
                    <input type="submit" value="Sign up for an organizational membership" class="button">
                </form>
                    <p></p>

                    <a name="GiftMemberships" id="GiftMemberships"></a>
                    <h2>Gift Memberships</h2>
                    <p>
                        You can purchase a Bookshare membership for someone with a qualifying
                        disability. You can also order a Braille book as a gift.
                        <a href="/_/membership/gift">Learn more about gift memberships</a>.
                    </p>
              

                </div><!--/panel-body-->

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/search_book.html.erb
  <div class="panel-heading"><h4><%=@book["title"]%></h4></div>
<div class="panel-body">	

<p>
	<b>Brief Synopsis: </b><%=@book["briefSynopsis"]%>
</p>

<p>
	<b>Complete Synopsis:</b> <%=@book["completeSynopsis"]%></p>
<hr>

<b>Book Quality: </b><%=@book["quality"]%>
    <br>
<b>ISBN-13: </b><%=@book["isbn13"]%>
    <br>
<b>Publisher: </b><%=@book["publisher"]%>
    <br>
<b>Date of Addition: </b><%=@book["publishDate"]%>
    <br>
<b>Copyright Date: </b><%=@book["copyright"]%>
    <br>
<b>Copyrighted By: </b><%=@book["author"][0]%>
    <br>
<!-- <b>Adult content: </b><%=@book["briefSynopsis"]%>
    <br> -->
<b>Language: </b><%=@book["language"]%>
   <br>
<b>Submitted By: </b> Bookshare Staff
    <br>

</div>

app/views/static_pages/search_text.html.erb
  <div class="panel-heading"><h4>Search Result for "<%=@search_txt%>"</h4></div>
<div class="panel-body">
	
	<%@searched_result.each do |result|%>
	<h1><a href="/static_pages/search_book?id=<%=result['id']%>"><%=result["title"]%></a></h1>
<p class="lead">
	by
	<a href="/static_pages/search_book?key=<%=result['author'][0]%>"><%=result["author"][0]%></a>
	<!-- <a href="index.php">Start Bootstrap</a> -->
</p>
<hr>
<p>
	<span class="glyphicon glyphicon-time"></span>
	Published by <%=result["publisher"]%> 
</p>

<p><%=result["briefSynopsis"]%></p>

<hr>
<%end%>
<%= will_paginate(@searched_result) %>
</div>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>